[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "shanghai"
optimizer = true
optimizer_runs = 0
viaIR = true

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

